# Generated by Django 4.1.2 on 2022-10-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bboard", "0002_rubric_alter_bb_options_alter_bb_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rubric",
            options={
                "ordering": ["name"],
                "verbose_name": "Рубрика",
                "verbose_name_plural": "Рубрики",
            },
        ),
    ]
