# Generated by Django 4.1.2 on 2022-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bboard", "0003_alter_rubric_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bb",
            options={
                "ordering": ["-published"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RemoveField(
            model_name="bb",
            name="price",
        ),
        migrations.AddField(
            model_name="bb",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="bb",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Заголовок"),
        ),
    ]
