# Generated by Django 4.1.2 on 2022-11-30 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bboard", "0004_alter_bb_options_remove_bb_price_bb_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bb",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="bb",
            name="image",
            field=models.ImageField(
                default="images/default_pic.jpg",
                null=True,
                upload_to="images",
                verbose_name="Картинка",
            ),
        ),
    ]
